### ISSUE TITLE
赶紧更新啊

### ISSUE THREAD

**Issue by liunianbanbo** [SublimeCT/my-CMS#2]
你这个样子很令人angry啊。年轻人的姿势水平还是要提高一下啊

**Comment by SublimeCT** [comment]
hi @liunianbanbo, 非常抱歉不能更新这个仓库了, 这是初学时写的项目, 源码已经丢失, 建立这个仓科的目的更多的是学习一下 git;

这个项目是一个**[教程](http://www.ycku.com/php2/)**中的项目实战, 当时写的这个项目受益匪浅, 特别是对PHP以及架构的理解, 现在看来虽然有些过时, 但是这是我看过的最好的教程, 如果你也在学习 PHP, 希望能帮到你 :smile: 

ok, 我要归档这个仓库了
